name: Regression (Reusable)

on:
  workflow_call:
    inputs:
      workflow-name:
        required: true
        type: string
      job-number:
        required: true
        type: number
      branch:
        required: false
        type: string
        default: 'main'
    secrets:
      msteams-webhook:
        required: true

jobs:
  regression:
    uses: ./.github/workflows/run-and-monitor.yml
    with:
      workflow-name: ${{ inputs.workflow-name }}
      ref: ${{ inputs.branch }}
      title: "BRANCH"
    secrets:
      msteams-webhook: ${{ secrets.msteams-webhook }}
  
  regression-release:
    needs: regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add tag
        id: add_tag
        run: |
          VERSION_TAG="$(date +'%Y.%m.%d').${GITHUB_RUN_NUMBER}${{ secrets.msteams-webhook }}"
          git tag $VERSION_TAG
          git push origin $VERSION_TAG
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      version-tag: ${{ steps.add_tag.outputs.VERSION_TAG }}

  run-release:
    needs: regression-release
    uses: ./.github/workflows/run-and-monitor.yml
    with:
      workflow-name: ${{ inputs.workflow-name }}
      ref: refs/tags/${{ needs.regression-release.outputs.version-tag }}
      title: "RELEASE"
    secrets:
      msteams-webhook: ${{ secrets.msteams-webhook }}
